services:
  db:
    image: bitnami/postgresql:latest
    container_name: api-books

    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}

    ports:
      - "5434:5432"

    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata: